services:
  node0:
    container_name: node0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../data/:/data/
    network_mode: host
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      - AVALANCHEGO_CHAIN_CONFIG_DIR=/data/chains
      - AVALANCHEGO_NETWORK_ID=fuji
      - AVALANCHEGO_DATA_DIR=/data/node0
      - AVALANCHEGO_PLUGIN_DIR=/plugins/
      - AVALANCHEGO_HTTP_PORT=9650
      - AVALANCHEGO_STAKING_PORT=9651
      - AVALANCHEGO_TRACK_SUBNETS=${AVALANCHEGO_TRACK_SUBNETS}
      - AVALANCHEGO_HTTP_ALLOWED_HOSTS=*
      - AVALANCHEGO_HTTP_HOST=0.0.0.0
