services:
  node0:
    container_name: node0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../data/:/data/
    network_mode: host
    command: /usr/local/bin/avalanchego --chain-config-dir=/data/chains --network-id=fuji --data-dir=/data/node0 --plugin-dir=/plugins/ --http-port=9650 --staking-port=9651 --track-subnets=2uteTaPwnKurZtV6Jy6ydZyRTxVTmznYMPn48TQ5nGHnFv3xzd
    user: "${CURRENT_UID}:${CURRENT_GID}"
  # node1:
  #   container_name: node1
  #   extends: node0
  #   command: /usr/local/bin/avalanchego --config-file=/data/configs/config-node1.json
  # node2:
  #   container_name: node2
  #   extends: node0
  #   command: /usr/local/bin/avalanchego --config-file=/data/configs/config-node2.json
  # node3:
  #   container_name: node3
  #   extends: node0
  #   command: /usr/local/bin/avalanchego --config-file=/data/configs/config-node3.json
  # node4:
  #   container_name: node4
  #   extends: node0
  #   command: /usr/local/bin/avalanchego --config-file=/data/configs/config-node4.json
