services:
  node0:
    container_name: node0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../data/:/data/
    network_mode: host
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      - TRACK_SUBNETS=${TRACK_SUBNETS}
      - NODE_NAME=node0
